[package]
name = "glove80-firmware-loader"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "firmware-loader"
path = "main.rs"

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
sysinfo = "0.30.5"
